###
POST http://localhost:8080/identity/auth/token
Content-Type: application/json

{
  "username": "hunglt.ee@gmail.com",
  "password": "1234"
}

###
POST http://localhost:8080/identity/auth/token
Content-Type: application/json

{
  "username": "new+4@example.com",
  "password": "1234"
}

###
POST http://localhost:8080/identity/auth/token
Content-Type: application/json

{
  "username": "admin@example.com",
  "password": "1234"
}

###
POST http://localhost:8080/identity/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDcwLCJpYXQiOjE3MzI2OTc4NzAsInVzZXJJZCI6IjIiLCJqdGkiOiJiY2M0MjVmMy05MjY1LTRlYzItOTA5Mi01ZTEyMzg0ZDI0YWYifQ.HuOoOPArOTfsLZ3OFlXaPmsGAhjtDZZZ0ROlZA9n92DdQ1lsog827AEf7YDiemRQc35UgXTaAJWi2sqVdbv5sg"
}

###
POST http://localhost:8080/identity/auth/introspect
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA"
}

###
POST http://localhost:8080/identity/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwiY3VzdG9tQ2xhaW0iOiJDdXN0b20iLCJzY29wZSI6IiIsImV4cCI6MTczMTkyNDU5NCwiaWF0IjoxNzMxOTIwOTk0LCJqdGkiOiIxYzUxYTUxMi01NDRmLTQ1OWMtOTY1ZC05ODMxNzQ2MzQzOWUifQ.z6sFqzGOpM3j3_xRhn3nWsiE4oidz_pL1wHqZetXo-IkXDVNME6Riz5EKJEbJJQUhB1yLnTeTflhE-7bo-ODgw"
}

###
GET http://localhost:8080/identity/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA

### OK
GET http://localhost:8080/identity/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA

###
GET http://localhost:8080/identity/users/my-info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA

###
GET http://localhost:8080/identity/permissions
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA

###
GET http://localhost:8080/identity/roles
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzAxNDgxLCJpYXQiOjE3MzI2OTc4ODEsInVzZXJJZCI6IjIiLCJqdGkiOiI3M2ExODliZS02M2Q0LTQzMWEtYThhOS02OTBkNjQ4Y2FkYzIifQ.xWQvNzC8GeBCFXYGBJt7T4bc2HbBnyweJk2ajRzMs9bW5_7db_kXc5mP7WHbhHQrm-XUBP8NwRdz_Fu7KeXMLA

###
http://localhost:8081/profile/users/ không được có dấu /
###
POST http://localhost:8081/profile/users
Content-Type: application/json

{
  "firstName": "firstName",
  "lastName": "lastName",
  "city": "Hanoi"
}

###
GET http://localhost:8081/profile/users/abe1f5b0-0a77-4e68-82b6-ffff38defe3a

###
POST http://localhost:8080/identity/users
Content-Type: application/json

{
  "username": "jame4",
  "password": "12345678",
  "firstName": "Jame4",
  "lastName": "Bond",
  "dob": "2000-04-08",
  "city": "Hanoi"
}

###
GET http://localhost:8081/profile/users/6655c655-0b91-4980-a4ab-c95b282c60df


###
POST http://localhost:8888/api/v1/identity/auth/token
Content-Type: application/json

{
  "username": "hunglt.ee@gmail.com",
  "password": "1234"
}

###
GET http://localhost:8888/api/v1/identity/users/my-info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwic2NvcGUiOiJST0xFX0FETUlOIiwiaXNzIjoiZGV2dGVyaWEuY29tIiwiZXhwIjoxNzMyNzgwODQxLCJpYXQiOjE3MzI3NzcyNDEsInVzZXJJZCI6IjIiLCJqdGkiOiJhY2MwZjhlNi1kNGVjLTRiOTYtOGY4Ny1mMTY0NTFiY2MyMjcifQ.Frhy1LAtnZl9H1qvVUsldTl6f_-owLsMeLBhwpdx_S1hu5G94xddEKlo1_pZ5EkPF8h8HAMNSKDWI9qRapjmHw

###
POST http://localhost:8081/profile/internal/users
Content-Type: application/json

{
  "firstName": "firstName",
  "lastName": "lastName",
  "city": "Hanoi"
}

### NOT FOUND
POST http://localhost:8888/api/v1/profile/internal/users
Content-Type: application/json

{
  "firstName": "firstName",
  "lastName": "lastName",
  "city": "Hanoi"
}

###
GET http://localhost:8081/profile/users

###
GET http://localhost:8888/api/v1/profile/users

###
POST http://localhost:8888/api/v1/identity/auth/token
Content-Type: application/json

{
  "username": "admin@example.com",
  "password": "1234"
}

###
GET http://localhost:8888/api/v1/profile/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkZXZ0ZXJpYS5jb20iLCJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTczMjc4ODE0NiwiaWF0IjoxNzMyNzg0NTQ2LCJqdGkiOiJhM2FiYjY1YS05MDU4LTRjODgtYmFjMi03MGUwOWRlYjJhMzYiLCJzY29wZSI6IlJPTEVfQURNSU4ifQ.jPDXTmWm9FgC3kIEPGt61sQj5m_QUEgNo9qnc6614kIRWt3IbaxAXwtoo4RJFTjttCikkooofztuqSZHeJViUQ

###
POST http://localhost:8888/api/v1/identity/auth/token
Content-Type: application/json

{
  "username": "new+4@example.com",
  "password": "1234"
}

### You do not have permission
GET http://localhost:8888/api/v1/profile/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkZXZ0ZXJpYS5jb20iLCJzdWIiOiJuZXcrNEBleGFtcGxlLmNvbSIsImV4cCI6MTczMjc4ODMzMiwiaWF0IjoxNzMyNzg0NzMyLCJqdGkiOiI4OGQ2NTAwZS03OThmLTRlMjQtYTZlOS0xZmVkMTRkMDY5YjciLCJzY29wZSI6IlJPTEVfVVNFUiJ9.sv1fCUcJIfw6LJHJsrKDsK5tD1gJCvy6nBc7l12vACJCawy6R6ChNZpVFn4u92P0F2K7naI1uMu5QF1gT8FBbw

###
POST http://localhost:8888/api/v1/identity/users/registration
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkZXZ0ZXJpYS5jb20iLCJzdWIiOiJodW5nbHQuZWVAZ21haWwuY29tIiwiZXhwIjoxNzMyNzkyNDkzLCJpYXQiOjE3MzI3ODg4OTMsImp0aSI6IjgxNjcxZmI5LTc5YjktNDRmNy05YzVkLTBlYWFhYTY4YWE3NSIsInNjb3BlIjoiUk9MRV9BRE1JTiJ9.uxNbZ2TWcciiQtMwisqkq_XLe0AxcVuBlMbQ9eXUqbrStiWHU29mw7mN60IbP7L9ohqMMo73YYc5deGBOZRElw
Content-Type: application/json

{
  "username": "new+6@example.com",
  "password": "12345678",
  "firstName": "A",
  "lastName": "A",
  "dob": "2000-10-01",
  "city": "Hanoi"
}

###
POST http://localhost:8888/api/v1/identity/users/registration
Content-Type: application/json

{
  "username": "new+7@example.com",
  "password": "12345678",
  "firstName": "A",
  "lastName": "A",
  "dob": "2000-10-01",
  "city": "Hanoi"
}
